# Generated by Django 5.0.1 on 2024-01-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://explorelompoc.com/wp-content/uploads/2021/06/food_placeholder.jpg', max_length=500),
        ),
    ]
